spring:
  application:
    name: ms-template

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/template}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true